free:
  max_replies_per_day: 5
  max_posts_per_day: 1
  max_emails_per_day: 1
  max_blogs_per_day: 1
  max_instagram_posts_per_day: 1

pro:
  max_replies_per_day: 30
  max_posts_per_day: 2
  max_emails_per_day: 5
  max_blogs_per_day: 3
  max_instagram_posts_per_day: 3
